---
apiVersion: v1
kind: Namespace
metadata:
  name: alphaverse
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: alpha
  name: alpha
  namespace: alphaverse
spec:
  containers:
  - name: alpha
    args:
    - /bin/tail
    - -f
    - /dev/null
    image: busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
